### ISSUE TITLE
本软件在进行802.1X验证时是否会在本地安装证书？

### ISSUE THREAD

**Issue by account8709** [SeaLoong/drcom4scut#28]
非计算机专业学生，但是听说该验证方式会安装相应证书，有担心被解密https的风险，期待回答。谢谢~

**Comment by SeaLoong** [comment]
程序本身不会安装，用到的库里我也没印象有说需要安装证书的

**Comment by account8709** [comment]
@SeaLoong 感谢回答！
另外我又去搜索了一下，本软件用的EAP验证方式似乎也是基于证书的验证方式？这是否也会有上述被解密https的风险呢

**Comment by SeaLoong** [comment]
这里用的EAP认证方式是MD5-Challenge，并不是基于证书的验证方式。
至于 被解密https 不是很能理解，客户端只是进行认证和维持心跳，并不是所有流量都会走校园网客户端，不知道被解密https的风险从何而来。

**Comment by account8709** [comment]
@SeaLoong 明白了，十分感谢！
